# Generated by Django 5.2.1 on 2025-08-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_no_accent",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
