# Generated by Django 5.2.1 on 2025-08-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
