# Generated by Django 5.2.1 on 2025-08-29 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0002_user_full_no_accent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="full_no_accent",
            new_name="full_name_no_accent",
        ),
    ]
