# Generated by Django 5.2.1 on 2025-08-18 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
