# Generated by Django 5.2.1 on 2025-09-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0003_rename_full_no_accent_user_full_name_no_accent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar_url",
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
