# Generated by Django 5.2.1 on 2025-09-08 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attachment", "__first__"),
        ("authenticate", "0004_remove_user_avatar_url_user_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.ForeignKey(
                blank=True,
                db_column="avatar_url_uid",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_fk_avatar_url",
                to="attachment.attachment",
            ),
        ),
    ]
