# Generated by Django 5.2.1 on 2025-09-09 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0005_user_avatar_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_deleted",
        ),
    ]
