# Generated by Django 5.2.1 on 2025-09-17 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import authenticate.models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0006_remove_user_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="resetpassword",
            name="token",
            field=models.CharField(
                db_index=True,
                default=authenticate.models.generate_token,
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Otp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_fk_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
