# Generated by Django 5.2.1 on 2025-09-17 01:56

from django.db import migrations, models

import authenticate.models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0007_alter_resetpassword_token_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpassword",
            name="token",
            field=models.CharField(
                db_index=True,
                default=authenticate.models.generate_token,
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="resetpassword",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
