# Generated by Django 5.2.1 on 2025-09-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0008_alter_resetpassword_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=10),
        ),
    ]
