# Generated by Django 5.2.1 on 2025-10-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0010_user_balance_user_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.FloatField(default=0.0),
        ),
    ]
