# Generated by Django 5.2.1 on 2025-10-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0011_alter_user_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pin",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
