# Generated by Django 5.2.1 on 2025-10-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0012_user_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pin",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
