# Generated by Django 5.2.1 on 2025-11-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0013_alter_user_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
