# Generated by Django 5.2.1 on 2026-01-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0014_user_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "admin"),
                    ("USER", "user"),
                    ("SUPERUSER", "superuser"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
