# Generated by Django 5.2.1 on 2026-01-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0015_user_role_alter_user_full_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="count_use_app",
            field=models.IntegerField(default=0),
        ),
    ]
