# Generated by Django 5.2.1 on 2025-06-02 07:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_name", models.TextField()),
                ("hashed_name", models.TextField()),
                ("size", models.IntegerField()),
                ("content_type", models.CharField(max_length=255)),
                ("bucket", models.CharField(max_length=255)),
                ("directory", models.TextField()),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_file_deleted", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_column="owner_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachment_fk_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        db_column="updater_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachment_fk_updater",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
