# Generated by Django 5.2.1 on 2025-09-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attachment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="type",
            field=models.CharField(
                choices=[
                    ("GROUP", "Group"),
                    ("USER", "User"),
                    ("EXPENSE", "Expense"),
                    ("MESSAGE", "Message"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=255,
            ),
        ),
    ]
