# Generated by Django 5.2.1 on 2025-06-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attachment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="type",
            field=models.CharField(
                choices=[
                    ("FOOD", "Food"),
                    ("DISH", "Dish"),
                    ("PORTION", "Portion"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=255,
            ),
        ),
    ]
