# Generated by Django 5.2.1 on 2025-06-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attachment", "0002_attachment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="public_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
