# Generated by Django 5.2.1 on 2025-10-08 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attachment", "0002_alter_attachment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="is_file_deleted",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="updater",
        ),
    ]
