# Generated by Django 5.2.1 on 2025-08-15 05:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("group", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.CharField(null=True)),
                ("ordinal", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "active"), ("DELETED", "deleted")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        db_column="group_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_fk_group",
                        to="group.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_fk_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
