# Generated by Django 5.2.1 on 2025-09-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="message",
            name="ordinal",
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "active"),
                    ("EDITED", "edited"),
                    ("DELETED", "deleted"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
