# Generated by Django 5.2.1 on 2025-09-13 13:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attachment", "0002_alter_attachment_type"),
        ("message", "0002_alter_message_options_remove_message_ordinal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attachment",
                    models.ForeignKey(
                        db_column="attachment_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_attachment_fk_attachment",
                        to="attachment.attachment",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        db_column="message_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_attachment_fk_message",
                        to="message.message",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["message", "attachment"],
                        name="message_mes_message_33ee4b_idx",
                    )
                ],
            },
        ),
    ]
