# Generated by Django 5.2.1 on 2025-09-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attachment", "0002_alter_attachment_type"),
        ("message", "0003_messageattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="message_fk_attachment",
                through="message.MessageAttachment",
                to="attachment.attachment",
            ),
        ),
    ]
