# Generated by Django 5.2.1 on 2025-11-11 17:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0004_message_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FRIEND_REQUEST", "Friend Request"),
                            ("FRIEND_ACCEPTED", "Friend Accepted"),
                            ("REMINDER", "Reminder"),
                            ("TRANSFER", "Transfer"),
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAW", "Withdraw"),
                            ("GROUP_CREATED", "Group Created"),
                            ("GROUP_UPDATED", "Group Updated"),
                            ("GROUP_LEFT", "Group Left"),
                            ("EVENT_CREATED", "Event Created"),
                            ("EVENT_UPDATED", "Event Updated"),
                            ("EVENT_DELETED", "Event Deleted"),
                            ("EXPENSE_CREATED", "Expense Created"),
                            ("EXPENSE_UPDATED", "Expense Updated"),
                            ("EXPENSE_RESTORED", "Expense Restored"),
                            ("EXPENSE_SOFT_DELETED", "Expense Soft Deleted"),
                            ("EXPENSE_HARD_DELETED", "Expense Hard Deleted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("related_uid", models.UUIDField(blank=True, null=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        db_column="from_user_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_fk_from_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_users",
                    models.ManyToManyField(
                        related_name="received_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
