# Generated by Django 5.2.1 on 2026-02-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0005_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("FRIEND_REQUEST", "Friend Request"),
                    ("FRIEND_ACCEPTED", "Friend Accepted"),
                    ("REMINDER", "Reminder"),
                    ("TRANSFER", "Transfer"),
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAW", "Withdraw"),
                    ("GROUP_CREATED", "Group Created"),
                    ("GROUP_UPDATED", "Group Updated"),
                    ("GROUP_LEFT", "Group Left"),
                    ("EVENT_CREATED", "Event Created"),
                    ("EVENT_UPDATED", "Event Updated"),
                    ("EVENT_DELETED", "Event Deleted"),
                    ("EXPENSE_CREATED", "Expense Created"),
                    ("EXPENSE_UPDATED", "Expense Updated"),
                    ("EXPENSE_RESTORED", "Expense Restored"),
                    ("EXPENSE_SOFT_DELETED", "Expense Soft Deleted"),
                    ("EXPENSE_HARD_DELETED", "Expense Hard Deleted"),
                    ("SYSTEM", "System"),
                    ("WARNING", "Warning"),
                    ("ANNOUNCEMENT", "Announcement"),
                ],
                max_length=50,
            ),
        ),
    ]
