# Generated by Django 5.2.1 on 2026-02-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0006_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_broadcast",
            field=models.BooleanField(default=False),
        ),
    ]
