# Generated by Django 5.2.1 on 2026-06-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0008_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="action_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CREATE", "create"),
                    ("UPDATE", "update"),
                    ("DELETE", "delete"),
                    ("AVAILABLE", "available"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("FRIEND_REQUEST", "Friend Request"),
                    ("FRIEND_ACCEPTED", "Friend Accepted"),
                    ("REMINDER", "Reminder"),
                    ("EVENT_REMIND", "Event Remind"),
                    ("TRANSFER", "Transfer"),
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAW", "Withdraw"),
                    ("GROUP_CREATED", "Group Created"),
                    ("GROUP_UPDATED", "Group Updated"),
                    ("GROUP_LEFT", "Group Left"),
                    ("EVENT_CREATED", "Event Created"),
                    ("EVENT_UPDATED", "Event Updated"),
                    ("EVENT_DELETED", "Event Deleted"),
                    ("EXPENSE_CREATED", "Expense Created"),
                    ("EXPENSE_UPDATED", "Expense Updated"),
                    ("EXPENSE_RESTORED", "Expense Restored"),
                    ("EXPENSE_SOFT_DELETED", "Expense Soft Deleted"),
                    ("EXPENSE_HARD_DELETED", "Expense Hard Deleted"),
                    ("EXPENSE_APPROVAL_REQUESTED", "Expense Approval Requested"),
                    ("EXPENSE_APPROVED", "Expense Approved"),
                    ("EXPENSE_APPROVAL_DECLINED", "Expense Approval Declined"),
                    ("SYSTEM", "System"),
                    ("WARNING", "Warning"),
                    ("ANNOUNCEMENT", "Announcement"),
                ],
                max_length=50,
            ),
        ),
    ]
