# Generated by Django 5.2.1 on 2025-08-15 07:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Friend",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("ACCEPTED", "accepted"),
                            ("BLOCKED", "blocked"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "friend",
                    models.ForeignKey(
                        db_column="friend_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_fk_friend",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_fk_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
