# Generated by Django 5.2.1 on 2025-08-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="message_request",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
