# Generated by Django 5.2.1 on 2025-09-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friend", "0002_friend_message_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "pending"), ("ACCEPTED", "accepted")],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
