# Generated by Django 5.2.1 on 2025-08-30 18:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
        ("group", "0004_group_name_no_accent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="group",
            field=models.ForeignKey(
                db_column="group_uid",
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_fk_group",
                to="group.group",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="name_no_accent",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "active"), ("DELETED", "deleted")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EventMember",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        db_column="event_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventmember_fk_event",
                        to="event.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_uid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventmember_fk_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
