# Generated by Django 5.2.1 on 2025-08-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_event_group_event_name_no_accent_event_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmember",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "active"), ("DELETED", "deleted")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
