# Generated by Django 5.2.1 on 2025-09-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_eventmember_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name_no_accent",
            field=models.TextField(blank=True, editable=False, max_length=255),
        ),
    ]
