# Generated by Django 5.2.1 on 2025-09-13 03:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_alter_event_name_no_accent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventmember",
            unique_together={("event", "user")},
        ),
    ]
