# Generated by Django 5.2.1 on 2025-10-12 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0005_alter_eventmember_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmember",
            name="event",
            field=models.ForeignKey(
                db_column="event_uid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_member_fk_event",
                to="event.event",
            ),
        ),
        migrations.AlterField(
            model_name="eventmember",
            name="user",
            field=models.ForeignKey(
                db_column="user_uid",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_member_fk_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
