# Generated by Django 5.2.1 on 2026-05-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0007_eventrestructuredebt_eventmemberbalance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "active"),
                    ("DELETED", "deleted"),
                    ("CLOSED", "closed"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
