# Generated by Django 5.2.1 on 2026-03-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payosorder",
            name="description",
            field=models.CharField(blank=True, default="", max_length=25),
        ),
    ]
