# Generated by Django 5.2.1 on 2026-03-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_alter_payosorder_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payosorder",
            name="description",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="payosorder",
            name="payment_link_id",
            field=models.CharField(default="", max_length=255),
        ),
    ]
