"""
Django settings for split_expense project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from typing import Optional

import dj_database_url
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = os.getenv("ENV", "dev")

if os.getenv("RENDER"):
    # Running on Render
    DEBUG = os.environ.get("DEBUG", "False") == "True"

    # Get the secret key from environment variables
    SECRET_KEY = os.environ.get("SECRET_KEY")
    if not SECRET_KEY:
        raise ValueError("SECRET_KEY must be set in environment variables")

    # Allow all hosts for now, but you should restrict this in production
    ALLOWED_HOSTS = ["*"]
else:
    # Local development
    if env not in ["dev", "staging", "prod"]:
        raise ValueError(f"Invalid env: {env}")

    load_dotenv(os.path.join(BASE_DIR, f"../env/.env.{env}"))

    SECRET_KEY = os.environ.get("SECRET_KEY")
    DEBUG = env == "dev"
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


INSTALLED_APPS = [
    "daphne",
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_crontab",
    "corsheaders",
    "whitenoise",
    "ninja_extra",
    # Local apps
    "authenticate",
    "event",
    "expense",
    "group",
    "message",
    "wallet",
    "friend",
    "my_admin",
    "user",
    "attachment",
]

# Custom user model
AUTH_USER_MODEL = "authenticate.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Custom middleware
    "utils.router.middleware.APIMiddleware",
]

ASGI_APPLICATION = "split_expense_system.asgi.application"
ROOT_URLCONF = "split_expense_system.urls"

if DEBUG:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }
if os.getenv("RENDER"):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [os.environ.get("REDIS_URL", "redis://localhost:6379/0")]
            },  # type: ignore
        }
    }

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates", BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if os.getenv("RENDER"):
    DATABASES = {
        "default": dj_database_url.config(
            default=os.getenv("DATABASE_URL"),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "split_expense_db"),
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "postgres"),
            "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

LOGIN_URL = "/admin/login/"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"

if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ACCESS_TOKEN_LIFETIME = int(os.getenv("ACCESS_TOKEN_LIFETIME", "15"))
REFRESH_TOKEN_LIFETIME = int(os.getenv("REFRESH_TOKEN_LIFETIME", "15"))
REFRESH_TOKEN_REMAIN = int(os.getenv("REFRESH_TOKEN_REMAIN", "1"))
RESET_PASSWORD_EXPIRES_IN_MINUTES = int(
    os.getenv("RESET_PASSWORD_EXPIRES_IN_MINUTES", "15")
)
OTP_LIFETIME = int(os.getenv("OTP_LIFETIME", 2))
# CORS
CORS_ALLOW_ALL_ORIGINS = True


# not run cronjob in render
# # CRONJOBS = [("0 0 * * *", "authenticate.management.commands.cleanup_expired_tokens")]
# CRONJOBS = [
#     ("0 0 * * *", "django.core.management.call_command", ["cleanup_expired_tokens"]),
# ]
# Sent email
def str_to_bool(value: Optional[str]) -> bool:
    return str(value).lower() in ("true", "1", "yes")


if os.getenv("SENDGRID_API_KEY"):
    EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
    SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
    SENDGRID_SANDBOX_MODE_IN_DEBUG = str_to_bool(
        os.getenv("SENDGRID_SANDBOX_MODE_IN_DEBUG")
    )
    SENDGRID_ECHO_TO_STDOUT = str_to_bool(os.getenv("SENDGRID_ECHO_TO_STDOUT"))
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@yourapp.com")

# S3
S3_BUCKET_NAME = os.getenv("S3_BUCKET_NAME")
S3_ACCESS_KEY_ID = os.getenv("S3_ACCESS_KEY_ID")
S3_SECRET_ACCESS_KEY = os.getenv("S3_SECRET_ACCESS_KEY")
S3_REGION = os.getenv("S3_REGION")
S3_PUBLIC_URL = os.getenv("S3_PUBLIC_URL")
S3_EXPIRES_IN = int(os.getenv("S3_EXPIRES_IN", "3600"))
