# Generated by Django 5.2.1 on 2025-08-15 06:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "deposit"),
                            ("WITHDRAWAL", "withdrawal"),
                            ("TRANSFER", "transfer"),
                        ],
                        default="DEPOSIT",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "active"), ("DELETED", "deleted")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=127, null=True),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        db_column="wallet_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_fk_wallet",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
