# Generated by Django 5.2.1 on 2025-10-15 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_account", "0002_remove_bankaccountwithdraw_wallet_and_more"),
        ("wallet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="from_wallet",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="to_wallet",
        ),
        migrations.RemoveField(
            model_name="walletdeposit",
            name="wallet",
        ),
        migrations.AddField(
            model_name="transaction",
            name="from_user",
            field=models.ForeignKey(
                db_column="from_user_uid",
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_fk_from_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="to_user",
            field=models.ForeignKey(
                db_column="to_user_uid",
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_fk_to_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="walletdeposit",
            name="user",
            field=models.ForeignKey(
                db_column="user_uid",
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet_deposit_fk_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Wallet",
        ),
    ]
