# Generated by Django 5.2.1 on 2025-10-15 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_remove_transaction_from_wallet_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="from_user",
            field=models.ForeignKey(
                db_column="from_user_uid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_fk_from_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="to_user",
            field=models.ForeignKey(
                db_column="to_user_uid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_fk_to_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
