# Generated by Django 5.2.1 on 2025-10-17 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_account", "0003_delete_bankaccountwithdraw"),
        ("wallet", "0003_alter_transaction_from_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Withdraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("code", models.CharField(editable=False, max_length=30, unique=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        db_column="bank_account_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_account_withdraw_fk_bank_account",
                        to="bank_account.bankaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_account_withdraw_fk_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
