# Generated by Django 5.2.1 on 2025-10-17 09:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0004_withdraw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="withdraw",
            name="id",
        ),
        migrations.AddField(
            model_name="withdraw",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
