# Generated by Django 5.2.1 on 2025-10-29 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0011_remove_restructuredebt_status"),
        ("wallet", "0005_remove_withdraw_id_withdraw_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="group",
            field=models.ForeignKey(
                blank=True,
                db_column="group_uid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_fk_group",
                to="group.group",
            ),
        ),
    ]
