# Generated by Django 5.2.1 on 2025-11-05 02:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0006_transaction_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="walletdeposit",
            name="date",
        ),
        migrations.RemoveField(
            model_name="withdraw",
            name="date",
        ),
        migrations.AddField(
            model_name="withdraw",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
