# Generated by Django 5.2.1 on 2026-06-01 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0008_alter_event_status"),
        ("wallet", "0007_remove_walletdeposit_date_remove_withdraw_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="event",
            field=models.ForeignKey(
                blank=True,
                db_column="event_uid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_fk_event",
                to="event.event",
            ),
        ),
    ]
