# Generated by Django 5.2.1 on 2025-10-17 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank_account", "0002_remove_bankaccountwithdraw_wallet_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BankAccountWithDraw",
        ),
    ]
