from enum import Enum, unique

from django.db.models import TextChoices


@unique
class StatusEnum(TextChoices):
    ACTIVE = "ACTIVE", "active"
    DELETED = "DELETED", "deleted"


@unique
class StatusMessageEnum(TextChoices):
    ACTIVE = "ACTIVE", "active"
    EDITED = "EDITED", "edited"
    DELETED = "DELETED", "deleted"


@unique
class FriendStatusEnum(TextChoices):
    PENDING = "PENDING", "pending"
    ACCEPTED = "ACCEPTED", "accepted"
    BLOCKED = "BLOCKED", "blocked"


@unique
class CurrencyEnum(TextChoices):
    AED = "AED", "United Arab Emirates dirham"
    AFN = "AFN", "Afghan afghani"
    ALL = "ALL", "Albanian lek"
    AMD = "AMD", "Armenian dram"
    ANG = "ANG", "Netherlands Antillean guilder"
    AOA = "AOA", "Angolan kwanza"
    ARS = "ARS", "Argentine peso"
    AUD = "AUD", "Australian dollar"
    AWG = "AWG", "Aruban florin"
    AZN = "AZN", "Azerbaijani manat"
    BAM = "BAM", "Bosnia and Herzegovina convertible mark"
    BBD = "BBD", "Barbados dollar"
    BDT = "BDT", "Bangladeshi taka"
    BGN = "BGN", "Bulgarian lev"
    BHD = "BHD", "Bahraini dinar"
    BIF = "BIF", "Burundian franc"
    BMD = "BMD", "Bermudian dollar"
    BND = "BND", "Brunei dollar"
    BOB = "BOB", "Boliviano"
    BRL = "BRL", "Brazilian real"
    BSD = "BSD", "Bahamian dollar"
    BTN = "BTN", "Bhutanese ngultrum"
    BWP = "BWP", "Botswana pula"
    BYN = "BYN", "Belarusian ruble"
    BZD = "BZD", "Belize dollar"
    CAD = "CAD", "Canadian dollar"
    CDF = "CDF", "Congolese franc"
    CHF = "CHF", "Swiss franc"
    CLP = "CLP", "Chilean peso"
    CNY = "CNY", "Chinese yuan"
    COP = "COP", "Colombian peso"
    CRC = "CRC", "Costa Rican colón"
    CUP = "CUP", "Cuban peso"
    CVE = "CVE", "Cape Verdean escudo"
    CZK = "CZK", "Czech koruna"
    DJF = "DJF", "Djiboutian franc"
    DKK = "DKK", "Danish krone"
    DOP = "DOP", "Dominican peso"
    DZD = "DZD", "Algerian dinar"
    EGP = "EGP", "Egyptian pound"
    ERN = "ERN", "Eritrean nakfa"
    ETB = "ETB", "Ethiopian birr"
    EUR = "EUR", "Euro"
    FJD = "FJD", "Fijian dollar"
    FKP = "FKP", "Falkland Islands pound"
    FOK = "FOK", "Faroese króna"
    GBP = "GBP", "Pound sterling"
    GEL = "GEL", "Georgian lari"
    GGP = "GGP", "Guernsey pound"
    GHS = "GHS", "Ghanaian cedi"
    GIP = "GIP", "Gibraltar pound"
    GMD = "GMD", "Gambian dalasi"
    GNF = "GNF", "Guinean franc"
    GTQ = "GTQ", "Guatemalan quetzal"
    GYD = "GYD", "Guyanese dollar"
    HKD = "HKD", "Hong Kong dollar"
    HNL = "HNL", "Honduran lempira"
    HRK = "HRK", "Croatian kuna"
    HTG = "HTG", "Haitian gourde"
    HUF = "HUF", "Hungarian forint"
    IDR = "IDR", "Indonesian rupiah"
    ILS = "ILS", "Israeli new shekel"
    IMP = "IMP", "Manx pound"
    INR = "INR", "Indian rupee"
    IQD = "IQD", "Iraqi dinar"
    IRR = "IRR", "Iranian rial"
    ISK = "ISK", "Icelandic króna"
    JEP = "JEP", "Jersey pound"
    JMD = "JMD", "Jamaican dollar"
    JOD = "JOD", "Jordanian dinar"
    JPY = "JPY", "Japanese yen"
    KES = "KES", "Kenyan shilling"
    KGS = "KGS", "Kyrgyzstani som"
    KHR = "KHR", "Cambodian riel"
    KID = "KID", "Kiribati dollar"
    KMF = "KMF", "Comorian franc"
    KRW = "KRW", "South Korean won"
    KWD = "KWD", "Kuwaiti dinar"
    KYD = "KYD", "Cayman Islands dollar"
    KZT = "KZT", "Kazakhstani tenge"
    LAK = "LAK", "Lao kip"
    LBP = "LBP", "Lebanese pound"
    LKR = "LKR", "Sri Lankan rupee"
    LRD = "LRD", "Liberian dollar"
    LSL = "LSL", "Lesotho loti"
    LYD = "LYD", "Libyan dinar"
    MAD = "MAD", "Moroccan dirham"
    MDL = "MDL", "Moldovan leu"
    MGA = "MGA", "Malagasy ariary"
    MKD = "MKD", "Macedonian denar"
    MMK = "MMK", "Burmese kyat"
    MNT = "MNT", "Mongolian tögrög"
    MOP = "MOP", "Macanese pataca"
    MRU = "MRU", "Mauritanian ouguiya"
    MUR = "MUR", "Mauritian rupee"
    MVR = "MVR", "Maldivian rufiyaa"
    MWK = "MWK", "Malawian kwacha"
    MXN = "MXN", "Mexican peso"
    MYR = "MYR", "Malaysian ringgit"
    MZN = "MZN", "Mozambican metical"
    NAD = "NAD", "Namibian dollar"
    NGN = "NGN", "Nigerian naira"
    NIO = "NIO", "Nicaraguan córdoba"
    NOK = "NOK", "Norwegian krone"
    NPR = "NPR", "Nepalese rupee"
    NZD = "NZD", "New Zealand dollar"
    OMR = "OMR", "Omani rial"
    PAB = "PAB", "Panamanian balboa"
    PEN = "PEN", "Peruvian sol"
    PGK = "PGK", "Papua New Guinean kina"
    PHP = "PHP", "Philippine peso"
    PKR = "PKR", "Pakistani rupee"
    PLN = "PLN", "Polish złoty"
    PYG = "PYG", "Paraguayan guaraní"
    QAR = "QAR", "Qatari riyal"
    RON = "RON", "Romanian leu"
    RSD = "RSD", "Serbian dinar"
    RUB = "RUB", "Russian ruble"
    RWF = "RWF", "Rwandan franc"
    SAR = "SAR", "Saudi riyal"
    SBD = "SBD", "Solomon Islands dollar"
    SCR = "SCR", "Seychellois rupee"
    SDG = "SDG", "Sudanese pound"
    SEK = "SEK", "Swedish krona"
    SGD = "SGD", "Singapore dollar"
    SHP = "SHP", "Saint Helena pound"
    SLE = "SLE", "Sierra Leonean leone"
    SOS = "SOS", "Somali shilling"
    SRD = "SRD", "Surinamese dollar"
    SSP = "SSP", "South Sudanese pound"
    STN = "STN", "São Tomé and Príncipe dobra"
    SYP = "SYP", "Syrian pound"
    SZL = "SZL", "Swazi lilangeni"
    THB = "THB", "Thai baht"
    TJS = "TJS", "Tajikistani somoni"
    TMT = "TMT", "Turkmenistan manat"
    TND = "TND", "Tunisian dinar"
    TOP = "TOP", "Tongan paʻanga"
    TRY = "TRY", "Turkish lira"
    TTD = "TTD", "Trinidad and Tobago dollar"
    TVD = "TVD", "Tuvaluan dollar"
    TWD = "TWD", "New Taiwan dollar"
    TZS = "TZS", "Tanzanian shilling"
    UAH = "UAH", "Ukrainian hryvnia"
    UGX = "UGX", "Ugandan shilling"
    USD = "USD", "United States dollar"
    UYU = "UYU", "Uruguayan peso"
    UZS = "UZS", "Uzbekistani som"
    VES = "VES", "Venezuelan bolívar"
    VND = "VND", "Vietnamese đồng"
    VUV = "VUV", "Vanuatu vatu"
    WST = "WST", "Samoan tālā"
    XAF = "XAF", "Central African CFA franc"
    XCD = "XCD", "East Caribbean dollar"
    XDR = "XDR", "Special drawing rights"
    XOF = "XOF", "West African CFA franc"
    XPF = "XPF", "CFP franc"
    YER = "YER", "Yemeni rial"
    ZAR = "ZAR", "South African rand"
    ZMW = "ZMW", "Zambian kwacha"
    ZWL = "ZWL", "Zimbabwean dollar"


@unique
class TransactionTypeEnum(TextChoices):
    DEPOSIT = "DEPOSIT", "deposit"
    WITHDRAWAL = "WITHDRAWAL", "withdrawal"
    TRANSFER = "TRANSFER", "transfer"


@unique
class SplitTypeEnum(TextChoices):
    EQUAL = "EQUAL", "equal"
    PERCENTAGE = "PERCENTAGE", "percentage"
    CUSTOM = "CUSTOM", "custom"


@unique
class SortTypeEnum(Enum):
    ASC = "asc"
    DESC = "desc"
