# Generated by Django 5.2.1 on 2025-08-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0002_groupmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "active"), ("DELETED", "deleted")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
