# Generated by Django 5.2.1 on 2025-08-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0003_groupmember_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="name_no_accent",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
