# Generated by Django 5.2.1 on 2025-09-08 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0004_group_name_no_accent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="avatar_url",
        ),
    ]
