# Generated by Django 5.2.1 on 2025-09-09 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0006_group_avatar_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupmember",
            unique_together={("user", "group")},
        ),
        migrations.AddIndex(
            model_name="groupmember",
            index=models.Index(
                fields=["user", "group"], name="group_group_user_ui_2e24e5_idx"
            ),
        ),
    ]
