# Generated by Django 5.2.1 on 2025-09-25 14:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0007_alter_groupmember_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="RestructureDebt",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "active"), ("DELETED", "deleted")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "creditor",
                    models.ForeignKey(
                        db_column="creditor_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restructure_debt_fk_creditor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "debtor",
                    models.ForeignKey(
                        db_column="debtor_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restructure_debt_fk_debtor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        db_column="group_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restructure_debt_fk_group",
                        to="group.group",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
