# Generated by Django 5.2.1 on 2025-10-28 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0010_restructuredebt_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restructuredebt",
            name="status",
        ),
    ]
