# Generated by Django 5.2.1 on 2026-02-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0011_remove_restructuredebt_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="last_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
