# Generated by Django 5.2.1 on 2026-04-15 14:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0012_groupmember_last_read_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferConfirmToken",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_used", models.BooleanField(default=False)),
                (
                    "from_user",
                    models.ForeignKey(
                        db_column="from_user_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_confirm_token_fk_from_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        db_column="group_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_confirm_token_fk_group",
                        to="group.group",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        db_column="to_user_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_confirm_token_fk_to_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
