# Generated by Django 5.2.1 on 2026-05-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0014_group_debt_optimization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="debt_optimization",
            field=models.CharField(
                choices=[("GROUP", "Group"), ("EVENT", "Event")],
                default="EVENT",
                max_length=10,
            ),
        ),
    ]
