# Generated by Django 5.2.1 on 2026-05-24 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0008_alter_event_status"),
        ("group", "0015_alter_group_debt_optimization"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferconfirmtoken",
            name="event",
            field=models.ForeignKey(
                blank=True,
                db_column="event_uid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_confirm_token_fk_event",
                to="event.event",
            ),
        ),
    ]
