# Generated by Django 5.2.1 on 2026-01-22 16:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_admin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RatingMonthly",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("creat_date", models.DateField(auto_now_add=True)),
                ("rate", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        db_column="user_uid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_monthlies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
