# Generated by Django 5.2.1 on 2026-02-21 03:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_admin", "0002_ratingmonthly"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ratingmonthly",
            name="creat_date",
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("platform", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "divice_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("os_version", models.CharField(blank=True, max_length=50, null=True)),
                ("app_version", models.CharField(blank=True, max_length=50, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
