# Generated by Django 5.2.1 on 2026-02-21 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_admin", "0003_remove_ratingmonthly_creat_date_loginhistory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loginhistory",
            old_name="divice_model",
            new_name="device_model",
        ),
    ]
