# Generated by Django 5.2.1 on 2026-04-16 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_admin", "0004_rename_divice_model_loginhistory_device_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermonthlyactivity",
            name="user",
            field=models.ForeignKey(
                db_column="user_uid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_monthly_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
