# Generated by Django 5.2.1 on 2025-09-13 13:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attachment", "0002_alter_attachment_type"),
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="receipt_url",
        ),
        migrations.CreateModel(
            name="ExpenseAttachment",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attachment",
                    models.ForeignKey(
                        db_column="attachment_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_attachment_fk_attachment",
                        to="attachment.attachment",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        db_column="expense_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_attachment_fk_expense",
                        to="expense.expense",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="expense",
            name="receipt_url",
            field=models.ManyToManyField(
                db_index=True,
                related_name="expense_fk_receipt_url",
                through="expense.ExpenseAttachment",
                to="attachment.attachment",
            ),
        ),
        migrations.AddIndex(
            model_name="expenseattachment",
            index=models.Index(
                fields=["expense", "attachment"], name="expense_exp_expense_9eba6f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="expenseattachment",
            unique_together={("expense", "attachment")},
        ),
    ]
