# Generated by Django 5.2.1 on 2025-09-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attachment", "0002_alter_attachment_type"),
        ("expense", "0002_remove_expense_receipt_url_expenseattachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="receipt_url",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="expense_fk_receipt_url",
                through="expense.ExpenseAttachment",
                to="attachment.attachment",
            ),
        ),
    ]
