# Generated by Django 5.2.1 on 2025-09-02 03:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0002_userparticipatesinexpense"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-created_at"]},
        ),
    ]
