# Generated by Django 5.2.1 on 2025-09-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0003_alter_expense_receipt_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="remaind_at",
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_date",
            field=models.DateTimeField(),
        ),
    ]
