# Generated by Django 5.2.1 on 2025-09-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0004_remove_expense_remaind_at_alter_expense_expense_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
