# Generated by Django 5.2.1 on 2025-09-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0006_expense_updated_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersharesinexpense",
            old_name="status",
            new_name="status_paid",
        ),
        migrations.AddField(
            model_name="usersharesinexpense",
            name="deleted",
            field=models.CharField(
                choices=[("ACTIVE", "active"), ("DELETED", "deleted")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
