# Generated by Django 5.2.1 on 2025-10-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0007_rename_status_usersharesinexpense_status_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersharesinexpense",
            name="payer_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
