# Generated by Django 5.2.1 on 2025-10-27 01:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0008_usersharesinexpense_paier_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersharesinexpense",
            old_name="payer_amount",
            new_name="receiver_amount",
        ),
    ]
