# Generated by Django 5.2.1 on 2025-10-27 03:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0009_rename_payer_amount_usersharesinexpense_receiver_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersharesinexpense",
            name="status_paid",
        ),
    ]
