# Generated by Django 5.2.1 on 2026-05-24 19:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0010_remove_usersharesinexpense_status_paid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="paid_by",
        ),
        migrations.CreateModel(
            name="ExpensePaidBy",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "expense",
                    models.ForeignKey(
                        db_column="expense_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_paid_by_fk_expense",
                        to="expense.expense",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_paid_by_fk_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["expense", "user"],
                        name="expense_exp_expense_75f78b_idx",
                    )
                ],
                "unique_together": {("expense", "user")},
            },
        ),
    ]
