# Generated by Django 5.2.1 on 2026-05-25 15:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0011_add_expense_paid_by_remove_paid_by_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="pending_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CREATE", "create"),
                    ("UPDATE", "update"),
                    ("DELETE", "delete"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="pending_update_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "active"),
                    ("DELETED", "deleted"),
                    ("PENDING_APPROVAL", "pending approval"),
                    ("PENDING_UPDATE", "pending update"),
                    ("PENDING_DELETE", "pending delete"),
                    ("DECLINED", "declined"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ExpenseApproval",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("ACCEPTED", "accepted"),
                            ("DECLINED", "declined"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "create"),
                            ("UPDATE", "update"),
                            ("DELETE", "delete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "expense",
                    models.ForeignKey(
                        db_column="expense_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_approval_fk_expense",
                        to="expense.expense",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_approval_fk_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["expense", "user"],
                        name="expense_exp_expense_dd9dbe_idx",
                    )
                ],
                "unique_together": {("expense", "user")},
            },
        ),
    ]
