# Generated by Django 5.2.1 on 2026-06-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0012_add_expense_approval_and_pending_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="expenseapproval",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="expense",
            name="pending_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CREATE", "create"),
                    ("UPDATE", "update"),
                    ("DELETE", "delete"),
                    ("AVAILABLE", "available"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="expenseapproval",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "create"),
                    ("UPDATE", "update"),
                    ("DELETE", "delete"),
                    ("AVAILABLE", "available"),
                ],
                max_length=20,
            ),
        ),
    ]
